GET http://localhost:5000/test
Accept: application/json


#########

http://192.168.138.156:5000/test


#########

GET http://localhost:5000/1/result
Accept: application/json

#########

GET http://localhost:5000/2/result
Accept: application/json


##########

GET http://localhost:5000/duration
Accept: application/json


############

POST https://oawz3wjih1.execute-api.eu-central-1.amazonaws.com/cubes/team06/start
Auth: t7s9EUv3nOwk


############

POST https://oawz3wjih1.execute-api.eu-central-1.amazonaws.com/cubes/team06/config
Content-Type: application/json
Auth: t7s9EUv3nOwk


{
 "time": "2024-06-30 14:32:05",
 "config": {
 "1": "red",
 "2": "blue",
 "3": "red",
 "4": "yellow",
 "5": "",
 "6": "",
 "7": "yellow",
 "8": "red"
 }
}

############

POST https://oawz3wjih1.execute-api.eu-central-1.amazonaws.com/cubes/team06/end
Auth: t7s9EUv3nOwk